# The basic colors
foreground		          #F8F1EE
background            	#1C1F23
background_alt        	#1A001D
background_highlight  	#1A001D
selection_foreground    #1C1F23
selection_background	  #88C0D0

# Cursor colors
cursor                  #FFE6A0
cursor_text_color       #1C1F23

# URL underline color when hovering with mouse
url_color               #FFE6A0

# Kitty window border colors
active_border_color     #C7E0FF
inactive_border_color   #7A8099
bell_border_color       #FFF3C0

# OS Window titlebar colors
wayland_titlebar_color system
macos_titlebar_color system

# Tab bar colors
active_tab_foreground   #181926
active_tab_background   #D8A0FF
inactive_tab_foreground #D1ECFF
inactive_tab_background #0D0C14
tab_bar_background      #181926

# Colors for marks (marked text in the terminal)
mark1_foreground #1C1F23
mark1_background #C7E0FF
mark2_foreground #1C1F23
mark2_background #D8A0FF
mark3_foreground #1C1F23
mark3_background #6BC0E0

# The 16 terminal colors

# black
color0 #0D0F11
color8 #34383C

# red
color1 #e34b49
color9 #ef6663

# green
color2  #A8DD70
color10 #C7F090

# yellow
color3 #FFD87F
color11 #FFE9A5

# blue
color4  #70a3b5
color12 #b4d2de

# magenta
color5  #D27AD8
color13 #E4A0F0

# cyan
color6  #4DD6DD
color14 #6DEFFF

# white
color7  #F6EFEA
color15 #FFFFFF
