general {
  ignore_empty_input = true
  immediate_render = true
  fail_timeout = 1000
}


background {
  color = rgba(17,17,27) 
  path = ~/.config/hypr/wallpaper.png
  blur_passes = 3
}

##########################################################
# CENTRAL CARD
##########################################################

shape {
  monitor =

    size = 540, 650

    color = rgba(24,24,37,0.92)        # Mantle

    rounding = 24

    border_size = 2
    border_color = rgb(17,17,27)       # Crust

    halign = center
    valign = center

    position = 0,0
}

##########################################################
# TIME
##########################################################

label {
  monitor =

    text = $TIME

    color = rgb(cba6f7)

    font_family = JetBrainsMono Nerd Font
    font_size = 64

    halign = center
    valign = center

    position = 0,240
}

##########################################################
# DATE
##########################################################

label {
  monitor =

    text = cmd[update:60000] date +"%A · %d %B %Y"

    color = rgb(a6adc8)

    font_family = JetBrainsMono Nerd Font
    font_size = 18

    halign = center
    valign = center

    position = 0, 175
}

##########################################################
# AVATAR
##########################################################

image {
  monitor =

    path = ~/.config/user

    size = 140

    rounding = -1

    border_size = 3
    border_color = rgb(cba6f7)

    halign = center
    valign = center

    position = 0,-30
}

##########################################################
# USERNAME
##########################################################

label {
  monitor =

    text = $USER

    color = rgb(cba6f7)

    font_family = JetBrainsMono Nerd Font
    font_size = 22

    halign = center
    valign = center

    position = 0,75
}

##########################################################
# PASSWORD BOX
##########################################################

input-field {
  monitor =

    size = 380,60

    position = 0,-170

    halign = center
    valign = center

    rounding = -1

    outer_color = rgb(cba6f7)
    inner_color = rgb(17,17,27)

    outline_thickness = 2

    fade_on_empty = false

    font_family = JetBrainsMono Nerd Font
    font_color = rgb(cdd6f4)

    placeholder_text = 󰌾 Password

    hide_input = false

    dots_center = true
    dots_spacing = 0.30
    dots_size = 0.20

    check_color = rgb(203, 166, 247)
    capslock_color = rgb(203, 166, 247)
    fail_color = rgb(243, 139, 168)
    fail_text = 
}

##########################################################
# FINGERPRINT
##########################################################

auth {
  fingerprint {
    enabled = true
      ready_message = Scan fingerprint to unlock
      present_message = Scanning...
      retry_delay = 250
      fail_text = 
  }
}

label {
  monitor =
    text = $FAIL $ATTEMPTS[]
    color = rgb(243, 139, 168)
    font_family = JetBrainsMono Nerd Font
    font_size = 13
    halign = center
    valign = center
    position = 0,-280
}


label {
  monitor =

    text = 󰈷  $FPRINTPROMPT

    color = rgb(a6adc8)

    font_family = JetBrainsMono Nerd Font
    font_size = 15

    halign = center
    valign = center

    position = 0,-250
}

##########################################################
# KEYBOARD LAYOUT
##########################################################

label {
  monitor =

    text = 󰌌  $LAYOUT

    color = rgb(cba6f7)

    font_family = JetBrainsMono Nerd Font
    font_size = 16

    halign = right
    valign = bottom

    position = -30,30
}
