add_newline = false
follow_symlinks = true

format = """
$username\
$hostname\
$shell\
$localip\
$shlvl\
$singularity\
$kubernetes\
$directory\
$vcsh\
$fossil_branch\
$fossil_metrics\
$git_branch\
$git_commit\
$git_state\
$git_metrics\
$git_status\
$hg_branch\
$hg_state\
$pijul_channel\
$docker_context\
$package\
$c\
$cmake\
$cobol\
$daml\
$dart\
$deno\
$dotnet\
$elixir\
$elm\
$erlang\
$fennel\
$fortran\
$gleam\
$golang\
$guix_shell\
$haskell\
$haxe\
$helm\
$java\
$julia\
$kotlin\
$gradle\
$lua\
$nim\
$nodejs\
$ocaml\
$opa\
$perl\
$php\
$pulumi\
$purescript\
$python\
$quarto\
$raku\
$rlang\
$red\
$ruby\
$rust\
$scala\
$solidity\
$swift\
$terraform\
$typst\
$vlang\
$vagrant\
$zig\
$buf\
$nix_shell\
$conda\
$meson\
$spack\
$memory_usage\
$aws\
$gcloud\
$openstack\
$azure\
$nats\
$direnv\
$env_var\
$mise\
$crystal\
$custom\
$sudo\
$cmd_duration\
$fill\
$jobs\
$battery\
$time\
$status\
$os\
$container\
$netns\
$line_break\
$character"""

[fill]
symbol = ' '

[[battery.display]]
threshold = 15
style = 'bold bright-red blink'


[os]
disabled = false

[os.symbols]
Arch = '󰣇 '
Debian = ' '
Ubuntu = ' '
NixOS = '󱄅 '

[nix_shell]
symbol = '󱄅 '


[time]
disabled = false
format = '[  $time ]($style) '
time_format = '%T'
time_range = '00:00:00-23:59:59'
style = 'blue bold'

[character]
success_symbol = '[\$](bold bright-green)'
error_symbol = '[#](bold bright-red)'

[username]
style_user = 'bright-red bold'
style_root = 'bright-yellow blink bold'
format = '[$user]($style)'
disabled = false
show_always = false

[directory]
format = 'in(white) [$path]($style)[$read_only]($read_only_style) '
truncation_symbol = '.../'

[git_branch]
style = 'green bold'
symbol = ' '

[git_commit]
only_detached = false
tag_disabled = false
style = 'green dimmed'
tag_symbol = ' 󰓹 '

[git_state]
rebase = '  Rebasing '
merge = '  Merging '
revert = ' 󰹿 Reverting '
cherry_pick = '  Cherry Picking '
bisect = ' 󰃤 Bisecting '
am = ' 󰶋  Applying Mailbox '
am_or_rebase = '  /󰶋  '
style = 'bright-yellow blink'

[git_metrics]
disabled = false

[git_status]
conflicted = '󰢪 '
ahead = ' ${count}'
behind = ' ${count}'
diverged = '󰃻  ${ahead_count}  ${behind_count}'
up_to_date = ''
untracked = '󰷊 '
stashed = '󰪶 '
modified = '󱇧 '
staged = '󰝒 '
renamed = '󰪹 '
deleted = ' '
typechanged = '󱁹 '
style = 'bold bright-yellow'

[hostname]
style = 'red bold'
format = '[@](blue bold)[$hostname]($style) '
ssh_only = true

[shell]
bash_indicator = 'bash'
zsh_indicator = 'zsh'
fish_indicator = 'fish'
format = '[$indicator]($style) '
style = 'blue bold'
disabled = false

[package]
symbol = '󰏖 '

[cmake]
symbol = '󱗾 '

[gradle]
symbol = '󰟆 '

[java]
style = 'red bold'
symbol = ' '
